Fix lifetimes in `Layout::children`
hecrj/iced pull request #590
Opened 2020-10-31 15:54 UTC by Limeth

This change allows for chaining of `children` calls without having to bind the iterator to a local variable, and consequently also allows for the result to be returned from the current scope.

```rust
    pub fn get_content_layout_from_child_layout(child_layout: Layout<'_>) -> Layout<'_> {
        child_layout.children().nth(0).unwrap().children().nth(1).unwrap()
    }
```

2020-11-01 10:26 UTC, hecrj requested changes

2020-11-01 10:26 UTC, hecrj commented on native/src/layout.rs
> +    pub fn children(&self) -> impl Iterator<Item = Layout<'a>> + '_ {
It's probably better to simply take `self` by value here and drop the anonymous iterator lifetime, given that `Layout` implements `Copy`.

2020-11-02 15:30 UTC, Limeth commented
Thanks for the review, I applied the suggestions. Should be good to go now. :+1:

2020-11-02 16:57 UTC, hecrj approved these changes
Awesome. Thank you!

2020-11-02 16:57 UTC, merged